Project/GNU/mediainfo.spec

Minor changes backported from MediaConch .spec file (thanks to @Vascom)

Requires minimal version of libzen and libmediainfo for CLI and GUI

---

Source/GUI/WxWidgets/GUI_Main_Tree.cpp

Previously, the output was not as expected if an offset is at more that 4 GiB (the 4+ GiB offset were having more characters that the others, no more alignment), and small files were having too much digits in the offset.

Dynamic size of the offset string in the tree trace

---

Project/GNU/CLI/configure.ac
Project/GNU/GUI/configure.ac

The CMake scripts for libzen and libmediainfo don't use Libs_Static
so LIBS would always be empty. Additionally, the proper way to get
static libcurl libs is to use '--static --libs' when invoking
pkg-config.
To prevent regressions, do both checks for Libs_Static variable
and the new '--static --libs' and use both. It's kind of overlinking,
maybe, but should prevent regressions for now.

autotools: fix static linking with pkg-config

---

README.md

Add ZenLib and MediaInfoLib as dependencies for macOS in the README

---

Project/OBS/deb7.debian/mediainfo.pod
Project/OBS/deb9.debian/mediainfo.pod
debian/mediainfo.pod

I've added the following options for "--output" in the manpages:
* OLDXML
* JSON
* EBUCore / EBUCore_JSON
* PBCore / PBCore2
All 3 "mediainfo.pod" files I've found seemed to be identical.
So I've changed one and copied it over the others.

Updated manpage to include JSON,EBUCore,PBCore as options.

---

Source/GUI/VCL/GUI_Main.cpp

Addition to https://github.com/MediaArea/MediaInfo/pull/384, when the library returns a bad name (with only spaces).

Allow sub-elements in tree views, fix

---

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/Core.kt

(For coherency between calls, fixed in MediaInfoLib)

Android GUI: Use raw language when generating XML

---

Project/GNU/CLI/configure.ac

This can solve a very specific issue where pkg-config might be pkgconf and a specific flag might be needed for the output to match pkg-config

configure.ac: Use PKG_CONFIG variable before using pkg-config

---

Source/GUI/Qt/mainwindow.cpp

This PR replaces MediaInfo's built-in icons with icons from the local system theme in the Qt version.

Use system icons instead of built-in

---

Project/Snap/mediainfo/snapcraft.yaml

https://snapcraft.io/docs/removable-media-interface
This interface will allow mediainfo to access mounted media. This plug is not auto-enabled and requires and explicit command to activate.

Add removable-media plug

---

Project/MSVC2022/CLI/MediaInfo.vcxproj

The MSVC2022 project Includes point to the MSVC2019 projects for MediaInfoLib and ZenLib. Point to the MSVC2022 projects instead to prevent build failures on systems with only the v143 toolset.

Fix MSVC2022 project Includes

---

Source/GUI/Qt/columneditsheet.cpp

fixed `-Wreorder` warning detected during build with GCC:
```
In file included from ../../../Source/GUI/Qt/columneditsheet.cpp:7:
../../../Source/GUI/Qt/columneditsheet.h: In constructor ‘ColumnEditSheet::ColumnEditSheet(column, int, int, Core*, QWidget*)’:
../../../Source/GUI/Qt/columneditsheet.h:52:11: warning: ‘ColumnEditSheet::C’ will be initialized after [-Wreorder]
52 |     Core* C;
|           ^
../../../Source/GUI/Qt/columneditsheet.h:45:12: warning:   ‘column ColumnEditSheet::col’ [-Wreorder]
45 |     column col;
|            ^~~
../../../Source/GUI/Qt/columneditsheet.cpp:22:1: warning:   when initialized here [-Wreorder]
22 | ColumnEditSheet::ColumnEditSheet(column c, int pos, int nb, Core* C, QWidget *parent) :
| ^~~~~~~~~~~~~~~
```

Qt GUI: fixed -Wreorder warning

---

Source/GUI/Qt/configtreetext.cpp
Source/GUI/Qt/editsheet.cpp
Source/GUI/Qt/sheetview.cpp

- [values for `QT_VERSION`](https://doc.qt.io/archives/qt-4.8/qtglobal.html#QT_VERSION) were incorrect (expected Qt 64.x.y instead of Qt 4.x.y)
- drop invalid code under such incorrect version comparison
- drop [deprecated function](https://doc.qt.io/qt-5/qlayout-obsolete.html#setMargin) that was added since Qt 5, but [deprecated in 5.13](https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/kernel/qlayout.h?h=v5.15.8-lts-lgpl#n86)
correct equivalent already existed in the code, just was not called due to incorrect Qt version check

Qt GUI: fixed QT_VERSION macro usage

---

Source/GUI/Qt/columneditsheet.cpp
Source/GUI/Qt/editconfigtreetext.cpp
Source/GUI/Qt/editcustom.cpp

replaced QRegExp with QRegularExpression, it enables Qt 6 build (no any further changes are required), but breaks compatibility with Qt 4 (what is not big deal as for me)
in these particular cases it was enough jsut to replace, no changes to patterns are required

Qt GUI: get rid of obsolete QRegExp usage

---

Source/GUI/Qt/main.cpp

avoid scaling issues and blurred icons in menus on HighDPI screens
screenshots from KDE, left - no changes (master as is), right - with this fix (noticeable change for round icons)

Qt GUI: HighDPI support

---

Source/GUI/Qt/editsheet.cpp

cosmetic change: replaced `""` with `<>` for Qt headers

Qt GUI: fix Qt headers

---

Source/GUI/Qt/about.cpp
Source/GUI/Qt/about.h
Source/GUI/Qt/about.ui
Source/GUI/Qt/mainwindow.cpp
Source/Resource/Resources.qrc

- simplified layout without visual changes
- better resize behavior - keep "about text" aligned to top
- use SVG icon for "info" icon (HighDPI support)
- "OK" button is default button
- get app version "in place" instead of passing it
- use format string for "about text" instead of "keyword + replace"

Qt GUI: About dialog fixes

---

Project/BCB/GUI/MediaInfo_GUI.cbproj
Project/BCB/GUI/MediaInfo_GUI.cpp
Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Preferences_Sheet.cpp

Drop support of classic bcc32 compiler dues to missing c++11 features
[snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230731-3)

Use llvm bcc32c compiler for borland project

---

Project/MSVC2022/GUI/MediaInfo_GUI.vcxproj
Project/MSVC2022/MediaInfo_Qt/MediaInfo_Qt.vcxproj
Project/MSVC2022/MediaInfo_UWP/MediaInfo.vcxproj

The MediaInfo MSVC2022 build system (solution and projects) were referring to the MSVC2017 and MSVC2019 build environments for dependant projects.
Some cross-contaminaton may still exist in MSVC2019 and MSVC2017 build environments - others should check these.

only refer to VS2022 projects in VS2022 build system. fixes #773

---

Project/GNU/GUI/Makefile.am
Source/GUI/WxWidgets/GUI_Main.cpp
Source/GUI/WxWidgets/GUI_Main.h
Source/GUI/WxWidgets/GUI_Main_HTML.cpp
Source/GUI/WxWidgets/GUI_Main_Menu.cpp
Source/GUI/WxWidgets/GUI_Main_Text.cpp
Source/GUI/WxWidgets/GUI_Preferences.cpp
Source/GUI/WxWidgets/GUI_Preferences.h

+ Fix hardcoded font size
Fixes #346

Unix GUI: Add preferences dialog

---

Source/GUI/VCL/GUI_Main.cpp

This patch makes MediaInfo use Cascadia Mono font for views that use monospaced font if Cascadia Mono is available on the system. Cascadia Mono is the default font for Windows Terminal. Most updated Windows systems with Windows Terminal installed will have this font.
Reason for this change is that the current font does not scale properly. Notice that it does not scale as linearly as Cascadia Mono. Cascadia Mono also has smoother edges and is easier to read especially on high DPI scaling.
Comparison @ 100%
Comparison @ 150%
Comparison @ 200%

Windows GUI: Change monospaced font

---

Source/GUI/VCL/GUI_Main.cpp

Take DPI scaling into account when setting window size. This should prevent cases where one ends up with a very small window filled with large icons and text when using a very high DPI display with very high DPI scaling.
Before and after this patch on a QHD display with 150% scaling for example
The difference will be more with higher scaling.

Windows GUI: Improve window size for high DPI

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h

Change the dialog for opening folders to the same dialog used for opening files on modern Windows systems. This is the dialog that other applications use for opening folders.

Windows GUI: Change dialog for opening folders

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm

Two commits:
1. Noticed that there is code to handle opening multiple files simultaneously but the Open File dialog doesn't allow selecting multiple files. It is now enabled and multiple files can be selected and opened simultaneously.
2. Minor fix to the positioning of the new Open Folder dialog. It now consistently opens at the same position near the corner of MediaInfo's main window.

Windows GUI: Dialog fixes

---

Source/GUI/VCL/GUI_Main.cpp

Fix text view not displaying correct strings if view was previously switched to other views such as XML.
Not sure what is the root cause and whether this PR addresses the root cause but this PR does resolve #700.

Windows GUI: Fix text view strings

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h

Change sheet view default split ratio and make it resizable. Now it shows more of the bottom contents by default and also after maximizing window.
Also change default monospaced font to match other views. Missed this page when changing the default monospaced font the other day.
Resolves #500

Windows GUI: Sheet view improvements

---

Source/GUI/VCL/GUI_Main.cpp

When only a single file is open in MediaInfo, use that file's name and folder as the default when exporting instead of MediaInfo's AppData directory.
Not sure if can consider issue #741 as resolved since this PR is only for when there is a single file open.

Windows GUI: Use file folder and name as export default for single file

---

Source/GUI/VCL/GUI_Main.cpp

Due to https://github.com/MediaArea/MediaInfo/pull/851#issuecomment-2141248535

Windows GUI dark mode: avoid an unexpected popup 2

---

Source/GUI/VCL/GUI_Main.cpp

Ensure code that is only necessary to execute once on application start-up is not repeated every time FormShow is called such as when switching dark mode.
Resolves bugs mentioned in https://github.com/MediaArea/MediaInfo/pull/836#issuecomment-2126335967
Also makes dark mode switching faster.
PR #851 and #852 no longer needed. Now the view will not change when switching dark mode.

Windows GUI: Prevent repeated execution of certain code

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.h

Inject CSS style into the HTML to give it a dark mode.
Let me know if you want to make changes to how it looks.

Windows GUI: Dark mode for HTML view

---

Project/BCB/GUI/MediaInfo_GUI.cbproj
Source/GUI/VCL/GUI_Main.cpp

Implement delayed loading of `user32.dll` and use `GetDpiForWindow`. Should work on Windows 7 to 11 now.
Tested on Windows 7 VM at 100% and 125%
Tested on Windows 11 PC at 100% and 150%
Nothing unexpected noticed, all seems fine.

Windows GUI: Use older API for getting system DPI, update2

---

Source/GUI/VCL/GUI_Main.cpp

Enable loading files in subdirectories when the selected directory itself does not contain any files.
Resolves #868

Windows GUI: Fix opening subdirectories

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h

Clean-up temporary HTML file on exit and address cause of sheet view crashing on exit.
See https://github.com/MediaArea/MediaInfo/pull/871#issuecomment-2175843069 for more information.

Windows GUI: Improve app closing routine

---

Source/Common/Preferences.cpp
Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h

Enable user to save their preferences for application theme.
This is an implementation of the suggestion in https://github.com/MediaArea/MediaInfo/pull/836#issuecomment-2124305168 which I am only able to implement now after studying and figuring out how MediaInfo handle preferences.
Fixed in latest force push:
>Still needs more testing and to fix this bug that occurs when MediaInfo tries to start in dark mode:
This is something we ran into in the initial dark mode implementation. It is supposedly caused by changing the theme during form show. Before this, we worked around by setting the theme in the form creation part. However, we need to find another place for it now because we need to read the preferences to set the theme and can only do so after the preferences are initialized and …

Windows GUI: Implement theme preferences

---

Project/QMake/GUI/MediaInfoQt.pro
Source/GUI/Qt/easyviewwidget.cpp
Source/GUI/Qt/mainwindow.cpp
Source/GUI/Qt/mainwindow.ui
Source/GUI/Qt/sheetview.cpp

A collection of improvements made while I was exploring the Qt version of MediaInfo.
- Use MSVC2022 for building the x86_64 Windows build
- Changes to project file to successfully build using MSVC2022 including fixes for linker errors due to path issues
- Enable Control Flow Guard (CFG) for x86_64 Windows build
- Enables CFG as [strongly encouraged by Microsoft](https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard).
- For full protection, MediaInfoLib, ZenLib and zlib should be built with `/guard:cf` enabled in `Project | Properties | Configuration Properties | C/C++ | Code Generation` of their respective Visual Studio Projects.
- Reverts commit https://github.com/MediaArea/MediaInfo/commit/18b6e3ca7d52940c6b0a6a89aebd51672ee0db72
- This commit it is not cross-platform …

Qt GUI Improvements

---

Project/MSVC2019/CLI/MediaInfo.vcxproj
Project/MSVC2022/CLI/MediaInfo.vcxproj

Enable Control Flow Guard (CFG) and Control-flow Enforcement Technology (CET) / Hardware-enforced Stack Protection for all MSVC2019 and MSVC2022 CLI Release targets.
Also enable optimizations for MSVC2022 x64 Release build as per defaults to match the Win32 build. For some reason it was disabled.

CLI: Enable CFG, CET and optimizations

---

Source/GUI/VCL/GUI_Main.cpp

A more proper fix for text view not displaying correct strings if view was previously switched to other views such as XML.
After finding that the Qt and Linux version of MediaInfo do not exhibit the bug in issue #700, I took a look at this bug again and found what appears to be the root cause. With the root cause addressed, the previous 'fix' (more like workaround) is no longer needed.
Resolves #700

Windows GUI: Fix text view strings properly

---

Project/BCB/GUI/MediaInfo_GUI.cbproj
Release/Release_GUI_Windows_i386.bat
Release/Release_GUI_Windows_x64.bat
Source/Install/MediaInfo_GUI_Windows.nsi
Source/Install/MediaInfo_GUI_Windows_i386.nsi
Source/Install/MediaInfo_GUI_Windows_x64.nsi

Requires building 64-bit versions of ZenLib and zlib as well. For these two, no changes required other than enabling 64-bit.
Advantages of 64-bit version:
- Better performance?
- 05 seconds 988 milliseconds vs 09 seconds 258 milliseconds on a single folder test
- Large address aware
- High Entropy VA / High-entropy 64-bit address space layout randomization (ASLR)
Issues that may be related: #575 #788 #868

Windows GUI: Enable 64-bit version

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h
Source/GUI/VCL/GUI_Plugin.dfm

- Fix layout of Plugin install window
- Fix overlapping of buttons with text. Resolves [#913](https://github.com/MediaArea/MediaInfo/issues/913#issuecomment-2227054711).
- Use consistent letter case for ToolBar
- Change `Toolbar` to `ToolBar` to be consistent.
- Fix issues found by static analysis
- Fix the following issues found with [Cppcheck](https://github.com/danmar/cppcheck). Use `int` instead of `size_t` as [ItemIndex is of type `int`](https://docwiki.embarcadero.com/Libraries/Athens/en/Vcl.Controls.TCustomListControl.ItemIndex). `size_t` is unsigned and cannot be reliably compared with `-1`.
```
Id: knownConditionTrueFalse
CWE: 571
Condition 'ItemIndex_Save!=-1' is always true
Id: knownConditionTrueFalse
CWE: 570
Condition 'Position==-1' is always false
```
- Fix the following …

Windows GUI: Fixes

---

Source/GUI/VCL/GUI_Main.cpp

Snapshot: https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240827-3/MediaInfo_GUI_24.06.20240827_Windows_x64.exe

Windows GUI: Prevent graph plugin to use negative metrics

---

Release/Release_GUI_Windows_i386.bat
Release/Release_GUI_Windows_x64.bat
Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/Install/MediaInfo_GUI_Windows.nsi
Source/Install/MediaInfo_GUI_Windows_i386.nsi
Source/Install/MediaInfo_GUI_Windows_x64.nsi

Use Edge WebView2 for HTML and Graph view when available else fallback to IE.
This should work on Windows 7 to 11 both with and without Edge WebView2 Runtime installed.
Additional changes beyond this PR that are required to get WebView2 working:
- Install `EdgeView2 SDK 1.0.1054.31 by Microsoft` or `EdgeView2 SDK 1.0.2739.1 by Microsoft` from `GetIt Package Manager` in `C++Builder`.
Commits details:
- Use Edge Webview2 for HTML and Graph views
- Set TWebBrowser to prefer Edge WebView2
- Code additions to set the UDF directory. This ensures the WebView2 UDF will always be beside the Plugin folder that contains MediaInfo's config.
- Enable WebView2 native dark mode
- Code additions to override theme (WebView2 already automatically follows system theme) by injecting CSS
- Code changes to …

Windows GUI: Use Edge WebView2 for HTML/Graph view

---

Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h

Ensure correct order during start-up to prevent bugs. Also reverts d0c7c2c1b7c3ec3c85e47111598fbc8de4897d71.
Fixes #942 
Fixes #943

Windows GUI: Improve start-up initialization

---

Source/GUI/Qt/mainwindow.cpp
Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm

- Make VCL GUI Text views editable again due to requests
- Make Qt GUI Text view editable to match VCL GUI behaviour
- Reduce brightness of Text and Tree views in VCL GUI light mode to exactly match the brightness of Easy view and also other Windows apps such as Notepad.
Fix https://github.com/MediaArea/MediaInfo/pull/944#issuecomment-2465416491

Text view changes for Windows and Qt GUI

---

Source/GUI/VCL/GUI_About.dfm
Source/GUI/VCL/GUI_Export.dfm
Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Plugin.dfm
Source/GUI/VCL/GUI_Preferences.cpp
Source/GUI/VCL/GUI_Preferences.dfm
Source/GUI/VCL/GUI_Preferences_Custom.dfm
Source/GUI/VCL/GUI_Preferences_Language.dfm
Source/GUI/VCL/GUI_Preferences_Output.dfm
Source/GUI/VCL/GUI_Preferences_Sheet.dfm
Source/GUI/VCL/GUI_Web.dfm

Partial solution for #948
- Resize Preferences window and improve layout to ensure no tabs appear and that all languages that have long text strings are displayed fully without overflow/clipping.
- Make all modal windows spawn at the center of their parent window.
- Use VCL setting to make main form window centered instead of doing manually using code.

Windows GUI: Layout improvements

---

Project/QMake/GUI/MediaInfoQt.pro
Source/GUI/Qt/mainwindow.cpp

Use WebEngine for HTML view to render the HTML properly.

Qt GUI: Use WebEngine for HTML view

---

Source/GUI/VCL/GUI_Main.dfm

The final change for Tree and Text view background colour. Use the default colour selected by VCL / Windows for these kind of views. Any dissatisfaction is no longer the responsibility of MediaInfo's codes.

Windows GUI: Reset Text and Tree views colours to default

---

Source/GUI/Qt/mainwindow.cpp
Source/GUI/Qt/mainwindow.ui
Source/GUI/Qt/prefs.cpp
Source/GUI/Qt/prefs.ui

Qt GUI: Make toolbar moveable but prevent it from being detached
- Correction of 43289a54085aa55d5a881d94f1278a942138501e
- Turns out the toolbar was designed to be moveable. The main intention of the previous commit was to prevent toolbar from being detached from main window. Now it is moveable but must be docked to one of the four sides of the window.
Qt GUI: Save shell extension preference
- Prepare for future integration with IExplorerCommand-based shell extension on Windows.
- The saved preference can be read from registry by the IExplorerCommand implementation to decide if it should be visible.
Qt GUI: Add inform version and timestamp options
- Something that the VCL GUI has
Qt GUI: Add captions display options
- Match other toolkit versions

Qt GUI: Fixes and improvements

---

Project/QMake/GUI/MediaInfoQt.pro
Source/GUI/Qt/export.cpp
Source/GUI/Qt/export.h
Source/GUI/Qt/graphplugin.cpp
Source/GUI/Qt/graphplugin.h
Source/GUI/Qt/mainwindow.cpp
Source/GUI/Qt/prefs.cpp
Source/GUI/Qt/prefs.ui
Source/GUI/Qt/views.cpp
Source/GUI/Qt/views.h

Qt GUI: Revert 'Make Text view editable'
- Revert commit b9fbf9ec8aa9e15bebcc87eb4fe102f47fe56f5f as it broke drag and drop of files into the text view. Text view isn't supposed to be editable anyway so match the wxWidgets version instead of VCL one.
Qt GUI: Add legacy stream display option
- An option that is present in MediaInfoLib and CLI but not yet in the GUI
- Disabled by default
Qt GUI: Enable WithThread so that progress bar actually works
- There is progress bar implemented but it only flashes a split second after MediaInfo appears to hang while opening many files.
- This commit makes the progress bar serve its purpose
Qt GUI: Add FFmpeg plugin support
- Tested
Qt GUI: Add Graph view
- Qt GUI now has working graph view
| Light | Dark |
| - | - |
| ![Screenshot 2024-11-15 …

Qt GUI: Fixes and improvements 2

---

Source/Install/MediaInfo_GUI_Windows.nsi
Source/Install/MediaInfo_GUI_Windows_i386.nsi
Source/Install/MediaInfo_GUI_Windows_x64.nsi

- Use ExecWait for regsvr32 on install to avoid race conditions in case MediaInfo_Extensions_Install writes to same registry.
- Use ExecWait for regsvr32 on uninstall instead of waiting 3000 enabling uninstall to complete faster in most cases.
- Use UnInstallLib DLL to delete MediaInfo_InfoTip.dll on uninstall like with other DLLs to ensure it is cleanly removed after restart if it is still in use by Explorer.

Windows GUI: Installer improvements

---

Source/WindowsQtPackage/AppxManifest.xml

Lower Windows version requirement and add list of file extensions for FileExplorerContextMenus.

Qt GUI: Update MSIX manifest

---

Release/Release_GUI_Qt_Windows_x64_MSIX.cmd
Source/WindowsQtPackage/AppxManifest.xml

Exclude unused Qt libraries and make VC runtime an external dependency.
Now MSIX package size is 128MiB and installed size is 272MiB.

Qt GUI: Reduce size for Windows MSIX package

---

Release/Release_CLI_Windows_i386.bat
Release/Release_CLI_Windows_x64.bat
Release/Release_GUI_Windows_i386.bat
Release/Release_GUI_Windows_x64.bat

- Change quotes for `set BPATH` in Windows GUI/CLI release scripts to match what is done in `Release_GUI_Windows.bat`. This prevents failure if the path contains spaces or other characters that can cause issues.
- Remove `Preparing` section from `Release_GUI_Windows_i386.bat` as it is not present in `Release_GUI_Windows_x64.bat` and is not needed. The file that is attempted to copy/rename does not exist including its directory.

Release scripts improvements

---

Source/Install/MediaInfo_GUI_Windows.nsi
Source/Install/MediaInfo_GUI_Windows_i386.nsi
Source/Install/MediaInfo_GUI_Windows_x64.nsi

Fix https://github.com/MediaArea/MediaInfo/pull/960#issuecomment-2508390115

Windows GUI: Fix installer out path after assets

---

Project/QMake/GUI/MediaInfoQt.pro

Needs all the other zlib, ZenLib, MediaInfoLib and Qt PRs for ARM64 and EHCONT.
Tested to build and produce an ARM64 binary. However, Qt does not have pre-built ARM64 WebEngine and I do not have an ARM64 PC to test so this is not fully tested.

Qt GUI: Add Windows ARM64 build

---

Release/Release_GUI_Windows.bat
Source/Install/MediaInfo_GUI_Windows_Stub.nsi

There is still room for improvement/refinement...

Windows GUI: Add online/stub installer

---

Source/Install/MediaInfo_GUI_Windows.nsi
Source/Install/MediaInfo_GUI_Windows_ARM64.nsi
Source/Install/MediaInfo_GUI_Windows_Stub.nsi
Source/Install/MediaInfo_GUI_Windows_i386.nsi
Source/Install/MediaInfo_GUI_Windows_x64.nsi

Add ARM64 to all-in-one installer and update the other scripts for consistent layout.

Windows GUI: Update installers

---

Source/WindowsQtPackage/AppxManifest.xml
Source/WindowsSparsePackage/MSIX/AppxManifest.xml

Workaround Windows issue causing shell extension to not appear in classic context menus on certain systems.
As seen in https://github.com/MediaArea/MediaInfo/issues/994#issuecomment-2541700900 and https://github.com/MediaArea/MediaInfo/issues/994#issuecomment-2541738716.
I have no idea what letter works in our case so let us just try "C" since it worked for NanaZip.
Thanks to https://github.com/M2Team/NanaZip/pull/205.

Rename shell extension Verb Id

---

Source/WindowsQtPackage/AppxManifest.xml
Source/WindowsSparsePackage/MSIX/AppxManifest.xml

Workaround Windows issue causing shell extension to not appear in classic context menus on certain systems.
Continuation of #997

Rename shell extension Verb Id 2

---

.github/workflows/MediaInfo_Checks.yml
README.md

In Ubuntu 24.04 and newer, `libwxgtk3.2-dev` has replaced older libwxgtk3 versions. Recently, GitHub Actions `ubuntu-latest` runner image has upgraded to Ubuntu 24.04.
This PR updates the GitHub workflow file to fix the failed CI as well as updates the build instructions in README to match.

Fix CI and update README for building Linux GUI on Ubuntu 24.04

---

Source/GUI/Qt/mainwindow.cpp
Source/WindowsShellExtension/dllmain.cpp
Source/WindowsShellExtension/pch.h

Only works on new Windows 11 context menu. Windows File Explorer's classic context menu does not show any shell extensions for .url files.
[URL files for testing.zip](https://github.com/user-attachments/files/18409714/URL.files.for.testing.zip)

ShellExt: Handle .url files

---

Source/GUI/Qt/prefs.cpp
Source/GUI/Qt/prefs.ui
Source/GUI/VCL/GUI_Preferences.cpp
Source/GUI/VCL/GUI_Preferences.dfm
Source/GUI/VCL/GUI_Preferences.h
Source/WindowsShellExtension/dllmain.cpp

ShellExt: Option for separate instance

---

Source/Install/MediaInfo_GUI_Windows_EvergreenStub.nsi
Source/Install/MediaInfo_GUI_Windows_Stub.nsi

Add a version-less evergreen online/stub installer that will install the latest available suitable version for all Windows versions and architectures.
Also update the versioned online/stub installer to be consistent with the version-less one and simplify it.

Windows GUI: Add evergreen online/stub installer

---

Project/MSVC2022/CLI/MediaInfo.vcxproj
Source/CLI/CLI_Main.cpp

- Resolve all remaining warnings in CLI code as detected by Visual Studio Code analysis.
- Set C++20 standard in MSVC2022 project to match MediaInfoLib.
- Increase warning level to 3 in MSVC2022 project to help maintain code quality going forward since it can now build without a single warning at level 3.

Windows CLI: Resolve warnings + Set C++20 std and L3 warning for MSVC2022

---

Source/GUI/Qt/mainwindow.cpp
Source/GUI/Qt/mainwindow.h
Source/GUI/Qt/mainwindow.ui
Source/GUI/VCL/GUI_Main.cpp
Source/GUI/VCL/GUI_Main.dfm
Source/GUI/VCL/GUI_Main.h

- Windows GUI: Improve trace feature
- Enable switching back to 'Trace level - 0' after enabling higher levels without restarting MediaInfo.
- Use newer 'Trace_Level' instead of 'Details'.
- Rename 'Details' to 'Trace level'.
- Qt GUI: Add trace feature
- Implement trace feature.
- Only toggle between level 0 and 1.
- Screenshot:

Improve trace feature in VCL GUI and implement it in Qt GUI

---

Source/GUI/Qt/graphplugin.cpp

Good thing I decided to test the graph view on Linux. Turns out a fix is required as I did not think about the backslash previously when porting the code from Windows GUI.
Graph view now confirmed to work in Qt GUI on both Windows and Ubuntu.
Ubuntu screenshots below. Windows still works like previously (https://github.com/MediaArea/MediaInfo/pull/955#issue-2658712002).

Qt GUI: Make graph plugin work cross-platform

---

.github/workflows/MediaInfo-Qt_Checks.yml
Project/QMake/GUI/MediaInfoQt.pro
Project/QMake/GUI/install_nuget_packages.cmd
Release/Release_GUI_Qt_Windows_x64_MSIX.cmd
Source/GUI/Qt/mainwindow.cpp
Source/GUI/Qt/webview2widget.cpp
Source/GUI/Qt/webview2widget.h
Source/WindowsQtPackage/AppxManifest.xml

It works! :)
I don't know where to put the WebView2 SDK so I just put it in a 'ThirdParty' folder.
The MSIX size after translations and this PR is now around 32MiB. This is with Qt DLLs plus Graph and FFmpeg plugins. May be able to reduce further by removing some unused DLLs (if any remain) or by static linking.

Qt GUI: Use Edge WebView2 on Windows

---

Source/GUI/Qt/mainwindow.cpp
Source/GUI/Qt/prefs.cpp

Some font-related fixes for issues discovered on Ubuntu.
- Fix Preferences not showing the default currently used font correctly when there is no saved setting yet.
- Fix [QFontDatabase deprecated](https://doc.qt.io/qt-6/qfontdatabase-obsolete.html) warning that only appears on Ubuntu Qt Creator but not on Windows Qt Creator.

Qt GUI: Font-related fixes

---

.github/workflows/MediaInfo-Qt_Checks.yml

Turns out the CI did not actually build the ARM64 version of Qt GUI. Qt uses batch file for ARM64 `qmake` which links to x64 exe `qmake`. So a `call` is needed infront of qmake call for ARM64 else the command(s) in the following line(s) will not be executed.

Fix MediaInfo-Qt ARM64 CI

---

.gitignore

Tidy/clean-up `.gitignore` and make it consistent with MediaInfoLib for the MSVC section.
Nuget section is now an exact copy from https://github.com/github/gitignore/blob/main/VisualStudio.gitignore

Update .gitignore for MSVC

---

.github/workflows/MediaInfo_Checks.yml

Ubuntu ARM64 runner is now available on GitHub.
Changes:
- Update to `actions/checkout@v4`
- Parallelize `make` for faster CI completion
- Add a Ubuntu ARM64 build
- Test built CLI by running it
- Test is skipped for macos since the built CLI fails to run there
Note: Windows ARM64 runner is expected to be available soon within next few months.

Add Ubuntu ARM64 CI

---

Project/GNU/CLI/configure.ac
Project/GNU/GUI/configure.ac

Necessary for cross-compilation to work, where pkg-config will be set to ${CHOST}-pkg-config.

configure.ac: Use proper $PKG_CONFIG variable.

---

Source/GUI/Qt/mainwindow.cpp
Source/WindowsQtPackage/AppxManifest.xml

- Enable name display on Windows 10 tile
- Before and after:
- Fix font selection on Windows when Cascadia Mono in unavailable
Tested that everything is fine on Windows 10 and 11. It also has the correct look/design/theme depending on Windows version.
A test build of MediaInfo Qt GUI in MSIX is available here: https://github.com/cjee21/MediaInfo/actions/runs/14017355671
Since it is unsigned, it can be installed on Windows 11 with the following command in an Administrator PowerShell:
```powershell
Add-AppxPackage -Path MediaInfo_Qt_Windows_x64.msix -AllowUnsigned
```

Qt GUI: Fixes for Windows 10

---

.github/workflows/MediaInfo-Qt_Checks.yml
Project/QMake/GUI/MediaInfoQt.pro
Release/Release_GUI_Qt_Windows_x64_MSIX.cmd
Source/WindowsQtPackage/AppxManifest.xml

Fix Preferences window layout on older Qt versions used by some Linux distros due to change change to fully
qualified enumerations in `.ui` files for newer Qt (https://bugreports.qt.io/browse/QTBUG-126966). This is done by replacing the affected enumerations in `.ui` files when building with older Qt versions.
Some other fixes mainly for translations generation after the changes made in #1081.
Fixed layout on Ubuntu 24.04.2 using repo provided Qt 6.4.2:

Qt GUI: Fixes for Qt<6.7 and translations generation

---

Source/GUI/Qt/graphplugin.cpp
Source/GUI/Qt/graphplugin.h
Source/GUI/Qt/webview2widget.cpp
Source/GUI/Qt/webview2widget.h

Remove the imperfect Edge WebView2 size limitation workaround (#1087).
Use a temporary file for Graph view HTML to ensure large graphs can load and display properly in both Edge WebView2 and Qt WebEngine.
Tested on Windows + Edge WebView2 and Ubuntu + Qt WebEngine.

Qt GUI: Improve loading of large graphs in Graph view

---

Source/GUI/WxWidgets/GUI_Main.cpp

View_Refresh can be called from the base class destructor.
This causes a silent crash on close before the configuration file is written.
Fixes #1108

WX GUI: Fix crash with some wxGTK3 versions

---

Source/GUI/Qt/Qt_Translations_Updater/README.md
Source/GUI/Qt/Qt_Translations_Updater/update_Qt_translations.cmd
Source/GUI/Qt/Qt_Translations_Updater/update_Qt_translations.py
Source/GUI/Qt/Qt_Translations_Updater/update_Qt_translations.sh

As mentioned at https://github.com/MediaArea/MediaInfo/pull/1141#issuecomment-3140042194, now Qt translations no longer depends on `Languages.csv` so it is safe to be removed.

Qt GUI: Source translations from individual CSVs

---

.github/workflows/MediaInfo-Android_Checks.yml
.gitignore
README.md
Source/GUI/Android/app/build.gradle
Source/GUI/Android/app/src/main/AndroidManifest.xml
Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/AboutActivity.kt
Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/MediaInfoApplication.kt
Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailActivity.kt
Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt
Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SettingsActivity.kt
Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt
Source/GUI/Android/app/src/main/res/layout/activity_about.xml
Source/GUI/Android/app/src/main/res/layout/activity_report_detail.xml
Source/GUI/Android/app/src/main/res/layout/activity_report_list.xml
Source/GUI/Android/app/src/main/res/layout/activity_settings.xml
Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml
Source/GUI/Android/app/src/main/res/menu/menu_detail.xml
Source/GUI/Android/app/src/main/res/values-night/colors.xml
Source/GUI/Android/app/src/main/res/values-v23/styles.xml
Source/GUI/Android/app/src/main/res/values-v27/styles.xml
Source/GUI/Android/app/src/main/res/values/colors.xml
Source/GUI/Android/app/src/main/res/values/styles.xml
Source/GUI/Android/build.gradle

Migrate to Material 3 design and enable dynamic theming along with fixing invisible white status bar icons. Also make 'About' page scroll-able when needed (for example landscape mode on small devices or split screen).

Android GUI: Migrate to Material Design 3

---

.github/workflows/MediaInfo_Checks.yml
.gitignore
Project/CMake/CLI/CMakeLists.txt

build(cli): add cmake support

---

Project/CMake/CLI/CMakeLists.txt

The CLI built with CMake was missing name/description/company/version/copyright information.

CMake: Include resource file for CLI

---

.github/workflows/MediaInfo_Checks.yml

Not adding the `|| ''` causes the word 'false' to be inserted there which I missed when checking the run earlier.

CI: Fix syntax mistake
