MediaArea/MediaInfo

Project/GNU/mediainfo.spec
x Disable debuginfo package to fix Fedora 23 build
=> x Fix date in .spec changelog

History_CLI.txt, History_GUI.txt
=> Update history.txt files

Project/GNU/mediainfo.dsc, Project/GNU/mediainfo.spec, Project/OBS/deb6.debian/control, Project/OBS/deb6.dsc, Project/OBS/deb7.debian/control, Project/OBS/deb7.dsc, Project/OBS/deb9.debian/control, Project/OBS/deb9.dsc, debian/control
Signed-off-by: Almin <almin@almin.tf>
=> Incrementing ZL

Project/OBS/mga5.spec
Signed-off-by: Almin <almin@almin.tf>
=> Activate Mageia 5

Project/MSVC2015/CLI/MediaInfo.vcxproj, Project/MSVC2015/GUI/MediaInfo_GUI.vcxproj
Visual Studio : Support of 32-bit CPU without SSE
=> Visual Studio: DebugInformationFormat none in release mode

Project/GNU/mediainfo.spec
=> RPM license macro only available in fedora and RHEL/CentOS >= 7

Project/GNU/mediainfo.spec
=> Forgot a %endif in .spec file

Project/GNU/mediainfo.spec
=> Wrong doc files for GUI packages in .spec file

Source/GUI/WxWidgets/GUI_Main_Menu.cpp
=> + Linux/Mac: more output formats (PBCore, EBUCore, FIMS), update

Source/GUI/Cocoa/English.lproj/About.xib, Source/GUI/Cocoa/Language/en.txt, Source/GUI/Cocoa/Language/ru.txt
=> Update copyright for Mac App Store

Project/GNU/PKGBUILD
=> Add Arch PKGBUILD for OBS

Release/Release_All_Windows_i386.bat, Release/Release_All_Windows_x64.bat, Release/Release_CLI_GNU_Prepare.bat, Release/Release_CLI_Windows_i386.bat, Release/Release_CLI_Windows_x64.bat, Release/Release_GUI_GNU_Prepare.bat, Release/Release_GUI_Windows.bat, Release/Release_GUI_Windows_i386.bat, Release/Release_GUI_Windows_x64.bat, Release/Release_Source.bat
=> Unify binaries search paths

Project/GNU/mediainfo.dsc, Project/GNU/mediainfo.spec, Project/OBS/deb6.debian/control, Project/OBS/deb6.debian/rules, Project/OBS/deb6.dsc, Project/OBS/deb7.debian/control, Project/OBS/deb7.debian/rules, Project/OBS/deb7.dsc, Project/OBS/deb9.debian/control, Project/OBS/deb9.debian/rules, Project/OBS/deb9.dsc, debian/control, debian/rules
=> Add debug packages

Source/CLI/Help.cpp
Here's my best guess at what these should look like..
=> Add PBCore, Mediatrace and image sequence CLI help

README.md
=> Build info for Linux and Mac

Source/GUI/Cocoa/MediaInfo-Info.plist
=> Change CFBundleVersion value format

Project/OBS/deb9.debian/control, Project/OBS/deb9.dsc
=> Fix build on ubuntu-next

Source/GUI/Cocoa/MediaInfo.xcodeproj/xcshareddata/xcschemes/MediaInfo.xcscheme, Source/GUI/Cocoa/MediaInfo.xcodeproj/xcuserdata/mymac.xcuserdatad/xcschemes/xcschememanagement.plist
=> Add XCode scheme (needed by xcodebuild in archive mode)

Project/OBS/deb9.debian/control, Project/OBS/deb9.dsc
=> Remove now undeeded dependency (fix Debian Next)

Source/Common/Preferences.cpp, Source/Install/MediaInfo_Extensions.nsh
Add 3ga and 3gpa extensions handling
=> 3GA and 3GPA extensions add

Project/GNU/GUI/Makefile.am, Project/GNU/PKGBUILD, Project/GNU/mediainfo.spec, Project/OBS/deb6.debian/rules, Project/OBS/deb7.debian/mediainfo-gui.install, Project/OBS/deb7.debian/rules, Project/OBS/deb9.debian/mediainfo-gui.install, Project/OBS/deb9.debian/rules, debian/mediainfo-gui.install, debian/rules
=> Move installed (appdata, icons...) files to Makefile

Project/GNU/GUI/Makefile.am
=> Fix Makefile for RHEL/CentOS5

Project/AppImage/Recipe.sh
=> Fix AppImage deps

README.md
=> Add appveyor status to README.md

Project/OBS/deb7.debian/control, Project/OBS/deb9.debian/control, debian/control
=> Update libmediainfo and libzen required version

Project/OBS/deb9.debian/control
=> Fix deb9 dependencies

History_CLI.txt, History_GUI.txt
=> Preparing v0.7.92.1

Source/GUI/Cocoa/MediaInfo-Info.plist, Source/GUI/Cocoa/MediaInfo.entitlements, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj
=> Update Xcode project

Project/GNU/GUI/mediainfo-gui.appdata.xml
=> Update AppData file

Project/MSVC2013/MediaInfo.sln, Project/MSVC2015/MediaInfo.sln, Project/MSVC2017/MediaInfo.sln
=> MSVC: Using zlib version without ASM.

Project/OBS/deb9.debian/control
=> Fix ZenLib version

Release/Release_CLI_Windows_i386.bat, Release/Release_CLI_Windows_x64.bat, Release/Release_GUI_Windows.bat, Release/Release_GUI_Windows_i386.bat, Release/Release_GUI_Windows_x64.bat, Source/Install/MediaInfo_GUI_Windows.nsi
=> Add libcurl.dll to Windows archives

Source/GUI/Cocoa/English.lproj/MainMenu.xib, Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/MyWindowController.h, Source/GUI/Cocoa/MyWindowController.m
=> Add EBUCore 1.8 outputs to Cocoa GUI

Source/GUI/VCL/GUI_Export.dfm
Fix [bug](https://sourceforge.net/p/mediainfo/bugs/1047/) due to https://github.com/MediaArea/MediaInfo/pull/151
=> EBUCore v1.8 with acquisition metadata, update

Project/GNU/mediainfo.spec
=> Mageia 6 and Fedora Rawhide compatibility

Source/CLI/CLI_Main.cpp
=> cli: help fix

Source/Common/Core.cpp, Source/Common/Core.h, Source/GUI/Cocoa/English.lproj/MainMenu.xib, Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/MediaInfo-Info.plist, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj, Source/GUI/Cocoa/MyWindowController.h, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/VCL/GUI_Export.cpp, Source/GUI/VCL/GUI_Export.dfm, Source/GUI/VCL/GUI_Export.h, Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Main.dfm, Source/GUI/VCL/GUI_Main.h, Source/GUI/WxWidgets/GUI_Main.h, Source/GUI/WxWidgets/GUI_Main_Menu.cpp
=> Add EBUCore JSON output to GUI

Project/OBS/deb9.debian/control, Project/OBS/deb9.dsc
=> Add rename as build dependancy for deb9

Project/GNU/GUI/Makefile.am, Project/GNU/mediainfo.spec, Project/OBS/deb6.debian/mediainfo-gui.dirs, Project/OBS/deb6.debian/mediainfo-gui.install, Project/OBS/deb7.debian/mediainfo-gui.install, Project/OBS/deb9.debian/mediainfo-gui.install, debian/mediainfo-gui.install
=> Install desktop file for kde5

Project/BCB/GUI/MediaInfo_GUI.cbproj
=> Update BCB project

Release/Release_CLI_Windows_i386.bat, Release/Release_CLI_Windows_x64.bat, Release/Release_GUI_Windows_i386.bat, Release/Release_GUI_Windows_x64.bat, Source/Install/MediaInfo_GUI_Windows.nsi
=> Build with MSVC2017

Source/Install/MediaInfo_GUI_Windows.nsi
=> Fix version number in nsi file

.travis.yml
=> Update dependancies in .travis.yml

Source/CLI/Help.cpp
=> Help for EBUCore external metadata

Source/Common/Core.cpp, Source/Common/Core.h, Source/GUI/Cocoa/English.lproj/MainMenu.xib, Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/MyWindowController.h, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/VCL/GUI_Export.cpp, Source/GUI/VCL/GUI_Export.dfm, Source/GUI/VCL/GUI_Export.h, Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Main.dfm, Source/GUI/VCL/GUI_Main.h, Source/GUI/VCL/GUI_Preferences.cpp, Source/GUI/WxWidgets/GUI_Main.h, Source/GUI/WxWidgets/GUI_Main_Menu.cpp
=> Add JSON output to GUI

README.md
=> typos and fixes

Project/QMake/GUI/MediaInfoQt.pro, Source/GUI/Qt/export.cpp, Source/GUI/Qt/export.h, Source/GUI/Qt/export.ui, Source/GUI/Qt/main.cpp, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/mainwindow.ui, Source/GUI/Qt/prefs.ui
- Rename preference file to avoid name collision on case insensitive OS
- Remove unfinished language support
- Rework export dialog
- Remove not implemented CSV export format
=> Qt GUI update 2

Source/CLI/Help.cpp, Source/Common/Core.cpp, Source/Common/Core.h, Source/GUI/Cocoa/English.lproj/MainMenu.xib, Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/MyWindowController.h, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/Qt/export.cpp, Source/GUI/Qt/export.h, Source/GUI/Qt/mainwindow.cpp, Source/GUI/Qt/views.cpp, Source/GUI/Qt/views.h, Source/GUI/VCL/GUI_Export.cpp, Source/GUI/VCL/GUI_Export.dfm, Source/GUI/VCL/GUI_Export.h, Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Main.dfm, Source/GUI/VCL/GUI_Main.h, Source/GUI/VCL/GUI_Preferences.cpp, Source/GUI/WxWidgets/GUI_Main.h, Source/GUI/WxWidgets/GUI_Main_Menu.cpp
=> Add NISO Z39.87 output

Project/GNU/mediainfo.spec
=> Make rpm relocatable

Project/QMake/GUI/MediaInfoQt.pro
=> Support install target in qmake project

Project/Mac/Prepare_for_Xcode.sh, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj
=> Build only 64 bit binary for macStore

Source/GUI/VCL/GUI_Preferences.cpp
=> Add missing outputs entries in VCL GUI preferences

Source/GUI/Qt/mainwindow.h
=> Avoid collision with system defined enums

Project/QMake/GUI/AppxManifest.xml, Project/QMake/GUI/MediaInfoQt.pro, Project/QMake/GUI/mediainfo-gui.rc
=> Fix UWP project

Project/GNU/mediainfo.spec
=> RPM with version suffix for CentOS/RHEL

Project/GNU/mediainfo.spec
=> RPM spec: revert to %define for some complex macros

Project/GNU/mediainfo.spec
=> x Missing dependencies for mediainfo prefix package

Source/GUI/VCL/GUI_Main.cpp
=> Fix custom view

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/res/values/strings.xml
=> Handle signing in android build properties

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/AboutActivity.kt, Source/GUI/Android/app/src/main/res/layout/activity_about.xml, Source/GUI/Android/app/src/main/res/values/strings.xml
=> Android GUI: remove donate button

Project/QMake/GUI/AppxManifest.xml, Source/GUI/Qt/about.cpp
=> Windows Store: Remove donate button

Source/Install/MediaInfo_Extensions.nsh
=> x Missing MediaInfo entry in Windows context menu after update

Source/GUI/Android/app/src/main/AndroidManifest.xml, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt
=> Android GUI: register MediaInfo to open files

Source/Install/MediaInfo_Extensions.nsh
=> Fix Windows "Open with" for directories

Source/GUI/VCL/GUI_Main.dfm
=> x Incorrect display of the ampersand character in Windows GUI

Source/GUI/Qt/main.cpp, Source/GUI/Qt/mainwindow.cpp
=> Qt GUI: Strip program path from command line

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/proguard-rules.pro
=> Android GUI: Reduce apk size

Source/GUI/Android/build.gradle
=> Android GUI: Update Kotlin/Gradle version

Source/GUI/Android/app/build.gradle
=> Android GUI: split apks

Source/GUI/UWP/DataGrid.xaml.h
=> UWP GUI: Fix Windows runtime metadata validation

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/AndroidManifest.xml, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/Core.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscriptionManager.kt, Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml, Source/GUI/Android/app/src/main/res/layout/hello_layout.xml, Source/GUI/Android/app/src/main/res/layout/spinner_layout.xml, Source/GUI/Android/app/src/main/res/menu/menu_main.xml, Source/GUI/Android/app/src/main/res/values-night/colors.xml, Source/GUI/Android/app/src/main/res/values/strings.xml, Source/GUI/Android/app/src/main/res/values/styles.xml
=> Android GUI: Subscriptions and dark theme

Source/GUI/Android/app/build.gradle
=> Android GUI: Fix version code for split apks

Source/Resource/Plugin/Language/en.csv
Hello again, this was a quick cursive look, I notice e.g. Choregrapher -> Choreographer appears in other languages, I can correct those also just will do them in one go instead of one by one.
As for Program settings strings, Ill need to see where strings appear and what type of setting it is. i.e. checkbox/other.
Let me know what you need.
=> [en] Obvious typos fix

Source/GUI/Cocoa/English.lproj/About.xib, Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/English.lproj/Preferences.xib, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj, Source/GUI/Cocoa/MyWindowController.m
=> Cocoa GUI: Update to macOS10.14 SDK with Mojave's dark theme support

LICENSE, License.html, Project/GNU/GUI/mediainfo-gui.metainfo.xml, Project/MSVC2013/CLI/MediaInfo_CLI.rc, Project/MSVC2013/GUI/MediaInfo_GUI.rc, Project/MSVC2015/CLI/MediaInfo_CLI.rc, Project/MSVC2015/GUI/MediaInfo_GUI.rc, Project/MSVC2017/CLI/MediaInfo_CLI.rc, Project/MSVC2017/GUI/MediaInfo_GUI.rc, Project/MSVC2019/CLI/MediaInfo_CLI.rc, Project/MSVC2019/GUI/MediaInfo_GUI.rc, Project/OBS/deb7.debian/copyright, Project/OBS/deb9.debian/copyright, Source/GUI/Android/app/src/main/res/values/strings.xml, Source/GUI/Cocoa/Language/en.txt, Source/GUI/Cocoa/Language/ru.txt, Source/GUI/Cocoa/MediaInfoDLL/MediaInfoDLL_Static.h, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/Cocoa/SegmentedCellWithMenu.h, Source/GUI/Cocoa/SegmentedCellWithMenu.m, Source/GUI/Cocoa/SegmentedControlWithMenu.h, Source/GUI/Cocoa/SegmentedControlWithMenu.m, Source/GUI/Qt/about.ui, Source/GUI/UWP/AboutPage.xaml, Source/GUI/iOS/MediaInfo/AboutViewController.swift, debian/copyright
=> Update copyright year

Project/GNU/mediainfo.spec
=> Fix dependencies for Fedora 30

Source/GUI/iOS/MediaInfo/Info.plist
=> Fix version in file

Project/Mac/Make_MI_dmg.sh
=> Generate macOS < 10.13 compatible DMG

Source/GUI/Cocoa/TreeView.m
=> Cocoa GUI: fix OSX < 10.8

Project/GNU/mediainfo.spec
=> Fix spec file for Mageia 7

Project/GNU/GUI/mediainfo-gui.metainfo.xml
=> Add content rating and release infos to appdata xml

Source/GUI/Cocoa/MediaInfo.entitlements, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj, Source/GUI/Cocoa/MediaInfo.xcodeproj/xcshareddata/xcschemes/MediaInfo.xcscheme, Source/GUI/Cocoa/SubscriptionManager.m
=> Cocoa: Fix subscription sharing

Source/GUI/Cocoa/MyWindowController.m
=> Cocoa GUI: Fix file index

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/AboutActivity.kt, Source/GUI/Android/app/src/main/res/layout/activity_about.xml, Source/GUI/Android/app/src/main/res/values/strings.xml
=> Android GUI: Add email link to about page

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportViewModel.kt, Source/GUI/Android/app/src/main/res/layout-w900dp/report_list.xml, Source/GUI/Android/app/src/main/res/layout/activity_report_list.xml, Source/GUI/Android/app/src/main/res/layout/report_list.xml, Source/GUI/Android/app/src/main/res/values/dimens.xml, Source/GUI/Android/app/src/main/res/values/strings.xml
=> Android GUI: Add button for clearing all saved reports

Source/GUI/Cocoa/MyWindowController.m, Source/GUI/Cocoa/TreeView.h, Source/GUI/Cocoa/TreeView.m, Source/GUI/Qt/mainwindow.cpp, Source/GUI/VCL/GUI_Main.cpp
=> Allow sub-elements in tree views

Source/GUI/Cocoa/English.lproj/Preferences.xib, Source/GUI/Cocoa/English.lproj/Subscribe.xib, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/Cocoa/PreferencesWindowController.h, Source/GUI/Cocoa/PreferencesWindowController.m
=> Cocoa GUI: Select default view (paid only)

Source/GUI/Cocoa/CompareView.h, Source/GUI/Cocoa/CompareView.m, Source/GUI/Cocoa/English.lproj/CompareView.xib, Source/GUI/Cocoa/English.lproj/MainMenu.xib, Source/GUI/Cocoa/English.lproj/Subscribe.xib, Source/GUI/Cocoa/MyWindowController.h, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/Cocoa/TreeView.m, Source/GUI/Cocoa/oMediaInfoList.h, Source/GUI/Cocoa/oMediaInfoList.mm
- Add option for more detailled output (paid only)
- Add ability to close files from compare view
=> Cocoa GUI: Update

Source/GUI/Cocoa/oMediaInfoList.mm
=> Cocoa GUI: Fix reading of Complete_Get option

Project/Mac/Make_MI_dmg.sh
=> Enable hardened runtime in macOS packages

Source/GUI/Android/app/src/main/AndroidManifest.xml, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt
=> Android GUI: add MediaInfo to share menu

Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/MyWindowController.h, Source/GUI/Cocoa/MyWindowController.m
=> Cocoa GUI: add CSV export.

Source/GUI/Cocoa/MyWindowController.m
=> Cocoa GUI: Don't spawn progress dialog when opening one local file

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/proguard-rules.pro, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDao.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SettingsFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/res/values/strings.xml, Source/GUI/Android/app/src/main/res/xml/fragment_settings.xml, Source/GUI/Android/build.gradle
- Update dependencies
- Fix crash on some olds Android devices
- Remove (crashing?) subscribe button in preferences
=> Android GUI: update project

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscriptionManager.kt, Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml
=> Android GUI: Update payment API

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscriptionManager.kt
=> Android GUI: downgrade payment API dues to crashs

Source/GUI/Cocoa/AppController.h, Source/GUI/Cocoa/AppController.m, Source/GUI/Cocoa/English.lproj/MainMenu.xib, Source/GUI/Cocoa/English.lproj/PurchaseReport.xib, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj, Source/GUI/Cocoa/PurchaseReportController.h, Source/GUI/Cocoa/PurchaseReportController.m
=> Cocoa GUI: Add in-app purchase report

Source/GUI/Cocoa/English.lproj/PurchaseReport.xib
=> Cocoa GUI: Fix broken outlet

Source/GUI/Cocoa/AboutWindowController.m
=> Cocoa GUI: Update URL

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/Core.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt
=> Android GUI: Show thanks message only once

Source/GUI/Cocoa/CompareView.m, Source/GUI/Cocoa/English.lproj/CompareView.xib
=> Cocoa GUI: Columns reordering in compare view

Project/GNU/CLI/AddThisToRoot_CLI_compile.sh, Project/GNU/CLI/configure.ac, Project/GNU/GUI/AddThisToRoot_GUI_compile.sh, Project/GNU/GUI/configure.ac
=> Remove hardcoded obsolete SDK paths and target version for macOS

Source/Resource/Plugin/Language/ru.csv
All fields translated to English i.e. not translated are also removed.
=> Update Russian language file

Project/GNU/GUI/mediainfo-gui.metainfo.xml
=> Remove URL in appdata release description

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/Core.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/PagerAdapter.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDao.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportViewModel.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SettingsFragment.kt, Source/GUI/Android/app/src/main/res/layout/activity_report_detail.xml, Source/GUI/Android/app/src/main/res/values-w900dp/bools.xml, Source/GUI/Android/app/src/main/res/values/bools.xml
=> Android GUI: Add slide gesture

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscriptionManager.kt, Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml, Source/GUI/Android/app/src/main/res/values/strings.xml, Source/Resource/Plugin/Language/en.csv, Source/Resource/Plugin/Language/fr.csv
=> Android GUI: Add lifetime subscription option

Source/GUI/iOS/MediaInfo/Base.lproj/Main.storyboard, Source/GUI/iOS/MediaInfo/SubscribeViewController.swift, Source/GUI/iOS/MediaInfo/SubscriptionManager.swift, Source/GUI/iOS/MediaInfo/Templates/Core.strings, Source/GUI/iOS/MediaInfo/Templates/Main.strings, Source/Resource/Plugin/Language/en.csv, Source/Resource/Plugin/Language/fr.csv
=> iOS GUI: Add lifetime subscription option

Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml
=> Android GUI: Add separator in subscribe view

Source/GUI/Cocoa/_i18n/create_lang_strings.pl
=> Cocoa GUI: Ignore untranslated entries when loading language csv

Source/Common/Preferences.cpp, Source/Common/Preferences.h, Source/GUI/VCL/GUI_About.cpp, Source/GUI/VCL/GUI_Main.cpp
=> Translatable sponsor message

Source/GUI/Cocoa/English.lproj/TreeView.xib, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj, Source/GUI/Cocoa/MyWindowController.m, Source/GUI/Cocoa/TreeView.h, Source/GUI/Cocoa/TreeView.m
- Make linking to CloudKit libraries optionnal
- Fix open files dialog for macOS < 10.10
- Restore lines breaks in tree view
=> Cocoa GUI: Small fixes

Source/Common/Preferences.cpp
=> Fix sponsor message translation

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SettingsFragment.kt, Source/GUI/Android/app/src/main/res/values/arrays.xml, Source/GUI/Android/app/src/main/res/values/strings.xml, Source/GUI/Android/app/src/main/res/xml/fragment_settings.xml
=> Android GUI: Add "system default" uimode option

Project/GNU/CLI/configure.ac, Project/GNU/GUI/configure.ac
=> Autotools: Add arm architecture for macOS

Project/GNU/CLI/configure.ac, Project/GNU/GUI/configure.ac
=> Fix typo in configure.ac files

Source/GUI/iOS/MediaInfo/SubscriptionManager.swift
=> iOS GUI: Backup lifetime subscription state

Source/GUI/Cocoa/CompareView.m, Source/GUI/Cocoa/IndexedTableColumn.h, Source/GUI/Cocoa/IndexedTableColumn.m, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj, Source/GUI/Cocoa/MyWindowController.m
=> Cocoa GUI: Fix columns reordering in compare view

Project/Mac/BR_extension_CLI.sh, Project/Mac/BR_extension_GUI.sh, Project/Mac/Info.plist, Project/Mac/Prepare_for_Xcode.sh, Source/GUI/Cocoa/MediaInfo-Info.plist, Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj
+ Set minimal macOS version to 10.9 (10.10 for wxWidgets GUI)
=> Add arm64 architucture for macOS

Source/GUI/Cocoa/CompareView.h, Source/GUI/Cocoa/CompareView.m, Source/GUI/Cocoa/English.lproj/CompareView.xib, Source/GUI/Cocoa/TreeOutlineDelegate.h
=> Cocoa GUI: Break long fields in compare view

Source/CLI/Help.cpp, Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Preferences.cpp, Source/GUI/VCL/GUI_Preferences.dfm, Source/GUI/VCL/GUI_Preferences.h, Source/Resource/Plugin/Language/en.csv, Source/Resource/Plugin/Language/fr.csv
=> Option to add MediaInfoLib version to text report

Source/CLI/Help.cpp, Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Preferences.cpp, Source/GUI/VCL/GUI_Preferences.dfm, Source/GUI/VCL/GUI_Preferences.h, Source/Resource/Plugin/Language/en.csv, Source/Resource/Plugin/Language/fr.csv
=> Add creation date to text report

.github/workflows/MediaInfo_Checks.yml
=> Fix github-actions

Release/Release_CLI_Windows_i386.bat, Release/Release_CLI_Windows_x64.bat, Release/Release_GUI_Windows_i386.bat, Release/Release_GUI_Windows_x64.bat, Source/Install/MediaInfo_GUI_Windows.nsi
=> Use MSVC2019 for releases

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/AndroidManifest.xml, Source/GUI/Android/build.gradle, Source/GUI/Android/gradle/wrapper/gradle-wrapper.properties
=> Update to Android SDK 31

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscriptionManager.kt
=> Android GUI: update billing API

Source/GUI/Cocoa/MediaInfo.xcodeproj/project.pbxproj
- Global project update and cleaning
- Fix arm64 build
- Update signing process
=> Cocoa GUI: Update project

Project/GNU/PKGBUILD
=> Update Arch PKGBUILD

Source/GUI/Cocoa/English.lproj/MyWindow.xib, Source/GUI/Cocoa/MyWindowController.m
=> Cocoa GUI: fix tab order

Project/GNU/CLI/Makefile.am, Project/GNU/GUI/Makefile.am, Project/QMake/GUI/MediaInfoQt.pro
=> Enable C++11

Project/BCB/GUI/MediaInfo_GUI.cbproj, Source/GUI/VCL/GUI_Main.cpp
=> Windows GUI: Use dynamically linked MediaInfo DLL

Project/MSVC2022/GUI/MediaInfo_GUI.vcxproj
Fix after https://github.com/MediaArea/MediaInfo/pull/607.
=> MSVC2022 project files, update

Source/GUI/Cocoa/MediaInfo-Info.plist
=> Cocoa GUI: Update associated file list

Source/Common/Preferences.cpp, Source/GUI/VCL/GUI_About.cpp, Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Web.cpp
=> Windows GUI: Switch to https for MediaArea URLs

Project/GNU/mediainfo.spec
=> rpm: add support for rhel 9 and derivates

Source/GUI/WxWidgets/GUI_Main.cpp
Saves the current view on exiting the restores view on load in WxWidgets version.
can be disabled in config file.
=> remebers view on Linux GUI

Source/CLI/CLI_Main.cpp
Addition to https://github.com/MediaArea/MediaInfoLib/pull/1732.
=> S3: accept external crt file also for non geolocated URLs

Source/GUI/Cocoa/oMediaInfoList.mm, Source/GUI/VCL/GUI_Main.cpp
Just a name change.
Requires https://github.com/MediaArea/MediaInfoLib/pull/1809.
=> GUI: Add Conformance glossary button, update

Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/AndroidManifest.xml, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt
- Disable native file picker for android 4.4 (19)
- Replace ACTION_OPEN_DOCUMENT by ACTION_GET_CONTENT
=> Android GUI: Open files fixes

Source/GUI/VCL/GUI_Main.cpp
See https://github.com/MediaArea/MediaInfo/pull/836#issuecomment-2126335967.
=> Windows GUI dark mode: avoid an unexpected popup

Source/GUI/VCL/GUI_Main.cpp
Quick temporary fix that should prevent occurrence of bug mentioned at https://github.com/MediaArea/MediaInfo/pull/879#issuecomment-2182628248 after a MediaInfo update that contains updated translations.
=> Windows GUI: Quick temp fix for translations after update

Source/GUI/VCL/GUI_Main.dfm, Source/GUI/VCL/GUI_Main.h
=> Windows GUI: Add disabled toolbar icons

Source/GUI/VCL/GUI_Main.cpp
=> Windows GUI: Bold monospaced font

Source/GUI/VCL/GUI_Preferences.cpp, Source/GUI/VCL/GUI_Preferences.dfm
=> Windows GUI: Perfect the alignment in Preferences window

Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Main.dfm, Source/GUI/VCL/GUI_Preferences.cpp
=> Windows GUI: Fix some display issues

Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Main.dfm
=> Windows GUI: Improve text views & minor code fixes

Source/GUI/VCL/GUI_Export.dfm
=> Windows GUI: Improve layout of Export window

Project/QMake/GUI/mediainfo-gui.rc
Fix mismatched version numbers and blurry exe icon.
=> Qt GUI: Update resource file for Windows

Source/GUI/VCL/GUI_Main.cpp
Fix potential memory leak (my fault for the overlook) and simplify code for reading Windows theme registry.
=> Windows GUI: Fix potential memory leak

Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Preferences.cpp, Source/GUI/VCL/GUI_Preferences.dfm, Source/GUI/VCL/GUI_Preferences.h
Note: I did not implement translations for this preferences option.
=> Windows GUI: Add LegacyStreamDisplay option

Source/Install/MediaInfo_GUI_Windows.nsi, Source/Install/MediaInfo_GUI_Windows_i386.nsi, Source/Install/MediaInfo_GUI_Windows_x64.nsi, Source/Install/sign.cmd
Should make a test build before merging to ensure it works as expected on the build farm.
=> Windows GUI: Implement signing of uninstaller

Project/MSVC2022/CLI/MediaInfo.vcxproj
Needs https://github.com/MediaArea/zlib/pull/18, https://github.com/MediaArea/ZenLib/pull/163, https://github.com/MediaArea/MediaInfoLib/pull/2159.
=> Windows: Enable EH Continuation Metadata

Project/QMake/GUI/MediaInfoQt.pro
Needs https://github.com/MediaArea/zlib/pull/18, https://github.com/MediaArea/ZenLib/pull/163, https://github.com/MediaArea/MediaInfoLib/pull/2159.
=> Qt GUI: Enable EH Continuation Metadata for Windows x64

Source/Install/MediaInfo_GUI_Windows_i386.nsi, Source/Install/MediaInfo_GUI_Windows_x64.nsi
=> Windows GUI: Ensure correct installers are used for each system

.github/workflows/MediaInfo-Qt_Checks.yml, Source/GUI/Qt/translate.cpp
+ enable colour in msbuild output and use new format for flags
+ prevent 'unreferenced formal parameter' warning due to a work-in-progress part
=> Add Ubuntu for MediaInfo-Qt Checks

Source/GUI/iOS/MediaInfo/Core.swift, Source/GUI/iOS/MediaInfo/Info.plist, Source/GUI/iOS/MediaInfo/ReportsListViewController.swift, Source/GUI/iOS/MediaInfo/Templates/Core.strings, Source/Resource/Plugin/Language/en.csv, Source/Resource/Plugin/Language/fr.csv
=> iOS: Open from media gallery

Source/WindowsShellExtension/dllmain.cpp
Improve code quality and readability.
=> ShellExt: Code improvements

Source/GUI/VCL/GUI_Main.cpp
Fixes #1042 and somewhat improves #891.
=> Windows GUI: Fix menubar/toolbar visibility

Project/MSVC2022/MediaInfo_PackageHelper/MediaInfo_PackageHelper.vcxproj, Project/MSVC2022/MediaInfo_PackageHelper/packages.config, Project/MSVC2022/MediaInfo_WindowsShellExtension/MediaInfo_WindowsShellExtension.vcxproj, Project/MSVC2022/MediaInfo_WindowsShellExtension/packages.config
https://github.com/microsoft/wil/releases/tag/v1.0.250325.1
=> Update Windows Implementation Library

Source/GUI/Qt/graphplugin.cpp
Same bug likely affects VCL version since this code was copied from there to Qt version by me previously.
=> Qt GUI: Fix graph view

Release/Release_GUI_Qt_Windows_x64_MSIX.cmd
After #1099, it will be inside the Qt GUI exe.
=> Qt MSIX: Remove graph template from package

Source/GUI/Android/app/CMakeLists.txt, Source/GUI/Android/app/build.gradle, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportDetailFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/res/layout/activity_about.xml, Source/GUI/Android/app/src/main/res/layout/activity_settings.xml, Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml, Source/GUI/Android/build.gradle, Source/GUI/Android/gradle/wrapper/gradle-wrapper.properties
- Update to API 35
- Sets Minimum API to 21 (Android 5.0)
- Allows 16kb pagesize
- Update dependencies
=> Update Android project

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/MediaInfoApplication.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/ReportListActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SettingsFragment.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt, Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscriptionManager.kt, Source/GUI/Android/app/src/main/res/layout/activity_subscribe.xml
- Fix the lifetime of the SubscriptionManager object (unable to subscribe after opening the SettingsActivity issue).
- Fix cropped legal text on small-resolution devices.
=> Android GUI: Update billing API - fixes

Source/GUI/VCL/GUI_Main.cpp, Source/GUI/VCL/GUI_Sponsor.cpp, Source/GUI/VCL/GUI_Sponsor.dfm, Source/GUI/VCL/GUI_Sponsor.h, Source/Install/MediaInfo_SponsorPage.nsh
- Set the cursor to a hand when hovering (GUI and installer)
- Fix various scaling problems
- Fix the cropped image in hiDPI mode
- Fix the frame dimensions after maximising
[Snapshot](https://mediaarea.net/download/snapshots/branches/binary/mediainfo-gui/20250917_sponsor/MediaInfo_GUI_25.07.20250917_Windows.exe)
=> Sponsors widgets fixes

Source/GUI/Android/app/src/main/java/net/mediaarea/mediainfo/SubscribeActivity.kt
- Select the right price for yearly subscription
=> Android GUI: Update billing API - fixes 2

Source/Resource/Plugin/Language/pt-BR.csv
I'm sending an updated translation file. I've translated some common missing strings and fixed some spelling errors.
=> Update Portuguese Brazil (pt-BR) translation
